const utilities: Record<string, string> = {
  "site-header": "relative z-10 flex h-[76px] items-center justify-between bg-paper px-[7.5%] text-ink max-[640px]:h-[72px] max-[640px]:px-[6%] max-[900px]:px-[5%]",
  wordmark: "inline-flex flex-row items-center gap-3",
  "brand-logo": "block h-16 w-16 shrink-0 object-contain max-[640px]:h-[54px] max-[640px]:w-[54px]",
  "wordmark-name": "flex flex-col gap-1 text-sm font-bold tracking-[1.6px] text-ink max-[640px]:text-xs",
  "wordmark-name-em": "text-ink not-italic font-normal tracking-[1.6px]",
  "wordmark-name-small": "text-[6px] font-medium tracking-[1px] text-muted",
  "menu-toggle": "hidden h-[42px] w-[42px] cursor-pointer flex-col items-center justify-center gap-[6px] border-0 bg-transparent p-2 max-[640px]:flex",
  "menu-toggle-line": "h-px w-[22px] bg-ink transition-transform",
  "menu-toggle-open-first": "translate-y-[3.5px] rotate-45",
  "menu-toggle-open-last": "-translate-y-[3.5px] -rotate-45",
  "main-nav": "flex items-center gap-[clamp(22px,3vw,42px)] max-[900px]:gap-[18px] max-[640px]:invisible max-[640px]:absolute max-[640px]:left-0 max-[640px]:right-0 max-[640px]:top-[72px] max-[640px]:z-20 max-[640px]:flex-col max-[640px]:items-stretch max-[640px]:gap-0 max-[640px]:border-t max-[640px]:border-line max-[640px]:bg-paper max-[640px]:px-[6%] max-[640px]:pb-[22px] max-[640px]:pt-2",
  "main-nav-open": "max-[640px]:visible",
  "main-nav-link": "text-[11px] text-[#454c47] transition-colors hover:text-rust max-[640px]:border-b max-[640px]:border-line max-[640px]:py-[14px]",
  "nav-account-link": "text-[11px] text-ink transition-colors hover:text-rust max-[640px]:border-b max-[640px]:border-line max-[640px]:py-[14px]",
  "nav-cta": "inline-flex items-center gap-[17px] bg-[#5b2c17] px-[17px] py-[14px] text-[10px] text-white transition-colors hover:bg-[#9e562c] max-[640px]:mt-[14px] max-[640px]:justify-between",
  hero: "hero relative flex min-h-[clamp(460px,46vw,570px)] items-stretch justify-start overflow-hidden bg-espresso px-[7.5%] text-left max-[900px]:min-h-[535px] max-[900px]:px-[6%] max-[640px]:min-h-[635px] max-[640px]:px-[7%] max-[640px]:pb-[275px] max-[640px]:pt-[70px]",
  "hero-image": "hero-image absolute inset-y-0 right-0 z-0 w-[62%] bg-cover bg-center max-[640px]:inset-x-0 max-[640px]:bottom-0 max-[640px]:top-auto max-[640px]:h-[49%] max-[640px]:w-full",
  "hero-copy": "relative z-[1] my-0 w-1/2 max-w-[560px] self-center py-[28px] pb-[54px] text-left max-[900px]:w-[57%] max-[640px]:w-full max-[640px]:max-w-[440px] max-[640px]:self-start max-[640px]:pt-[50px]",
  "hero-eyebrow": "mb-6 flex items-center justify-start gap-[9px] text-[9px] font-bold tracking-[1.8px] text-[#e3ae75] max-[640px]:mb-[17px] max-[640px]:text-[7px] max-[640px]:tracking-[1.3px]",
  "eyebrow-line": "inline-block h-px w-[27px] bg-[#e3ae75]",
  "hero-title": "mb-[22px] max-w-[580px] text-[clamp(54px,5.4vw,76px)] font-medium leading-[1.01] tracking-[-4.2px] text-[#fffaf4] max-[900px]:text-[clamp(48px,6vw,63px)] max-[900px]:tracking-[-3.2px] max-[640px]:text-[clamp(48px,12vw,62px)] max-[640px]:leading-[1.04] max-[640px]:tracking-[-3px]",
  "hero-title-accent": "font-medium text-[#e3ae75]",
  "hero-description": "m-0 max-w-[370px] text-[13px] leading-[1.9] text-[#ead9c6] max-[640px]:max-w-[320px] max-[640px]:text-[11px]",
  "hero-actions": "mt-[30px] flex items-center justify-start gap-5 max-[640px]:mt-[23px]",
  "hero-button": "inline-flex items-center justify-between gap-[27px] bg-[#d18b4b] px-[18px] py-[15px] text-[10px] font-semibold text-espresso transition-colors hover:bg-[#e0a66d] max-[640px]:gap-[14px] max-[640px]:px-[14px] max-[640px]:py-[13px]",
  "hero-view-link": "text-[11px] text-[#f4f1e9] transition-colors hover:text-rust",
  "hero-link-arrow": "ml-[5px] text-[#e3ae75]",
  "hero-photo-caption": "absolute bottom-6 right-[7.5%] z-[1] flex items-center gap-[14px] text-[8px] tracking-[1.3px] text-[#f4f1e9] max-[900px]:right-[6%] max-[640px]:bottom-[19px] max-[640px]:right-[7%] max-[640px]:text-[7px]",
  "hero-caption-accent": "text-[#e3ae75]",
  "service-strip": "flex min-h-[62px] items-center gap-[clamp(24px,5vw,72px)] border-b border-line bg-[#ecebe3] px-[7.5%] max-[900px]:px-[6%] max-[640px]:min-h-[72px] max-[640px]:flex-wrap max-[640px]:justify-center max-[640px]:gap-x-[23px] max-[640px]:gap-y-[14px] max-[640px]:px-[5%] max-[640px]:py-4",
  "service-strip-item": "text-[9px] tracking-[1.1px] text-rust max-[640px]:text-[8px]",
  "service-strip-strong": "ml-2 text-[9px] font-semibold text-ink max-[640px]:text-[8px]",
  "service-strip-note": "ml-auto text-[8px] tracking-[1.2px] text-muted max-[640px]:hidden",
  "menu-section": "bg-paper px-[10.5%] py-[68px] max-[900px]:px-[7%] max-[640px]:px-[6%] max-[640px]:py-[62px]",
  "section-heading": "mx-auto mb-7 flex max-w-[1120px] items-end justify-between gap-[30px] text-left max-[640px]:mb-[25px] max-[640px]:flex-col max-[640px]:items-start max-[640px]:gap-3",
  "section-eyebrow": "mb-4 flex items-center gap-[9px] text-[8px] font-bold tracking-[1.55px] text-rust",
  "section-title": "m-0 text-[clamp(34px,3.8vw,46px)] font-medium leading-[1.1] tracking-[-2px] text-ink max-[640px]:text-[37px]",
  "section-title-accent": "font-medium text-rust",
  "section-intro": "mb-1 max-w-[300px] text-[11px] leading-[1.9] text-muted max-[640px]:m-0 max-[640px]:text-[10px]",
  "menu-grid": "mx-auto grid max-w-[1120px] grid-cols-3 gap-[18px] max-[900px]:gap-[15px] max-[640px]:grid-cols-2 max-[640px]:gap-x-[13px] max-[640px]:gap-y-[23px]",
  "menu-card": "min-w-0 animate-[arrive_600ms_ease_both]",
  "menu-card-image": "relative aspect-[1.1] overflow-hidden bg-[#e6e1d7] max-[640px]:aspect-[0.78]",
  "menu-card-img": "h-full w-full object-cover saturate-[0.82] transition-[filter,transform] duration-[450ms] hover:scale-[1.035] hover:saturate-100",
  "menu-card-details": "flex items-start justify-between gap-2 border-b border-line py-[14px] pb-[17px] max-[640px]:flex-col max-[640px]:gap-[2px] max-[640px]:py-[11px]",
  "menu-card-copy": "min-w-0",
  "menu-tag": "mb-[7px] block text-[7px] tracking-[1.1px] text-rust max-[640px]:text-[6px]",
  "menu-card-title": "mb-[5px] text-sm font-semibold text-ink max-[640px]:text-xs",
  "menu-note": "block text-[9px] text-muted max-[640px]:text-[8px]",
  "menu-price": "whitespace-nowrap pt-[15px] text-[13px] font-medium text-ink max-[640px]:pt-0 max-[640px]:text-xs",
  "menu-more": "mx-auto mt-[25px] flex w-max items-center justify-center gap-3 border border-[#c6ab8d] bg-transparent px-5 py-[13px] text-[10px] text-ink transition-colors hover:border-espresso hover:bg-[#f2e4d2]",
  "story-section": "grid min-h-[490px] grid-cols-[1.06fr_0.94fr] bg-[#432416] text-[#f8f2e9] max-[640px]:grid-cols-1",
  "story-image": "story-image min-h-[420px] bg-[#705039] max-[640px]:min-h-[290px]",
  "story-copy": "relative my-auto mx-auto max-w-[440px] px-[11%] py-[75px] max-[640px]:px-[8%] max-[640px]:py-[53px]",
  "story-eyebrow": "mb-[23px] flex items-center gap-[9px] text-[9px] font-bold tracking-[1.55px] text-[#d89b72]",
  "story-title": "mb-[23px] text-[clamp(37px,4vw,50px)] font-medium leading-[1.12] tracking-[-1.6px] text-[#f8f2e9] max-[640px]:text-[40px]",
  "story-title-accent": "font-medium text-[#e3ae75]",
  "story-paragraph": "text-[11px] leading-[1.9] text-[#d4c9be]",
  "story-link": "mt-[13px] inline-flex gap-[18px] border-b border-[#a9866a] pb-[9px] text-[10px] text-[#f4e8dc]",
  "story-link-arrow": "text-[#d89b72]",
  "story-mark": "absolute bottom-[33px] right-[12%] text-[8px] tracking-[1.5px] text-[#e3ae75]",
  "visit-section": "grid grid-cols-[0.95fr_1.05fr] gap-[13%] px-[10.5%] py-[88px] max-[900px]:gap-[7%] max-[900px]:px-[7%] max-[640px]:grid-cols-1 max-[640px]:gap-7 max-[640px]:px-[6%] max-[640px]:py-[62px]",
  "visit-eyebrow": "mb-[18px] flex items-center gap-[9px] text-[9px] font-bold tracking-[1.55px] text-rust",
  "visit-title": "m-0 text-[clamp(37px,4vw,50px)] font-medium leading-[1.08] tracking-[-1.5px] text-ink",
  "visit-title-accent": "font-medium text-rust",
  "visit-details": "pt-1",
  "visit-item": "grid grid-cols-[30px_1fr] gap-[22px] border-b border-line py-[19px] pb-[22px] first:border-t first:border-line",
  "visit-index": "pt-[3px] text-xs text-rust",
  "visit-item-title": "mb-[7px] text-[15px] font-semibold text-ink",
  "visit-item-description": "mb-[10px] max-w-[340px] text-[10px] leading-[1.8] text-muted",
  "detail-note": "text-[9px] text-rust",
  "detail-link": "inline-flex gap-3 text-[10px] text-rust",
  "site-footer": "grid min-h-[91px] grid-cols-4 items-center gap-5 bg-[#f0e1cf] px-[7.2%] py-5 max-[640px]:grid-cols-2 max-[640px]:gap-x-2 max-[640px]:gap-y-5 max-[640px]:px-[6%] max-[640px]:py-[23px]",
  "footer-copy": "m-0 text-[11px] italic text-muted max-[640px]:text-right max-[640px]:text-[10px]",
  "back-top": "text-[8px] tracking-[1px] text-ink",
  "footer-copyright": "text-[8px] text-muted max-[640px]:text-right",

  "auth-page": "relative isolate grid min-h-screen place-items-center overflow-hidden bg-[#333334] p-[13px] text-[#f2ece3]",
  "auth-card": "relative grid min-h-[650px] w-full max-w-[1320px] grid-cols-2 overflow-hidden rounded-[13px] border border-white/[.1] shadow-[0_24px_75px_rgb(13_11_10_/_35%)] max-[700px]:min-h-0 max-[700px]:grid-cols-1",
  "auth-art": "relative isolate flex min-h-full flex-col items-center justify-center overflow-hidden bg-[#f2ede3] p-[45px] text-center text-[#211f1e] before:absolute before:-right-[135px] before:-top-[155px] before:-z-10 before:h-[320px] before:w-[320px] before:rounded-full before:border before:border-[#ded7cc] before:content-[''] after:absolute after:-right-[105px] after:top-[20%] after:-z-10 after:h-[260px] after:w-[260px] after:rounded-full after:bg-[#e9e1d4] after:content-[''] max-[700px]:hidden",
  "auth-art-logo": "relative z-[1] mb-[26px] w-[198px] max-w-[55%] max-[900px]:w-[165px]",
  "auth-art-title": "relative z-[1] mb-[9px] text-[24px] leading-[1.2] tracking-[-.7px] [&>strong]:font-bold",
  "auth-art-copy": "relative z-[1] mb-[23px] text-[10px] text-[#806d5c]",
  "auth-art-tagline": "relative z-[1] text-[7px] tracking-[1.7px] text-[#9b5d32]",
  "auth-panel": "flex w-full flex-col justify-center self-stretch bg-[#211f1e] px-[clamp(36px,7vw,72px)] py-[48px] text-[#f3eee5] max-[700px]:px-[clamp(24px,8vw,54px)] max-[700px]:py-[42px] max-[420px]:px-5",
  "auth-panel-content": "mx-auto w-full max-w-[430px]",
  "auth-brand": "mb-[42px] inline-flex text-[11px] font-bold tracking-[1.5px] text-[#f3eee5] max-[700px]:mb-[32px]",
  "auth-brand-accent": "ml-1 font-normal not-italic text-[#d78b5a]",
  "auth-eyebrow": "mb-[10px] text-[8px] font-bold tracking-[1.8px] text-[#db8a55]",
  "auth-title": "mb-[7px] text-[clamp(29px,3.6vw,36px)] font-medium leading-[1.15] tracking-[-1.3px] text-[#f5f0e8]",
  "auth-subtitle": "mb-[20px] text-[10px] leading-[1.8] text-[#c5bbb0]",
  "auth-form": "flex flex-col gap-[8px] [&>label:not(.auth-check)]:mt-[6px] [&>label:not(.auth-check)]:text-[9px] [&>label:not(.auth-check)]:font-semibold [&>label:not(.auth-check)]:text-[#f0e9df] [&>input]:min-h-[39px] [&>input]:w-full [&>input]:rounded-[4px] [&>input]:border [&>input]:border-[#45413e] [&>input]:bg-[#302e2d] [&>input]:px-3 [&>input]:py-[9px] [&>input]:text-[11px] [&>input]:text-[#f4eee6] [&>input:focus]:border-[#d78b5a] [&>input:focus]:outline-none [&>input:focus]:ring-[3px] [&>input:focus]:ring-[#d78b5a]/[.18] [&_label.auth-check>input]:m-0 [&_label.auth-check>input]:h-[13px] [&_label.auth-check>input]:w-[13px] [&_label.auth-check>input]:accent-[#d78b5a]",
  "auth-label": "mt-[6px] text-[9px] font-semibold text-[#f0e9df]",
  "auth-input": "min-h-[39px] w-full rounded-[4px] border border-[#45413e] bg-[#302e2d] px-3 py-[9px] text-[11px] text-[#f4eee6] transition-[border-color,box-shadow] focus:border-[#d78b5a] focus:outline-none focus:ring-[3px] focus:ring-[#d78b5a]/[.18]",
  "auth-password-field": "relative block w-full",
  "auth-password-input": "min-h-[39px] w-full rounded-[4px] border border-[#45413e] bg-[#302e2d] py-[9px] pl-3 pr-11 text-[11px] text-[#f4eee6] focus:border-[#d78b5a] focus:outline-none focus:ring-[3px] focus:ring-[#d78b5a]/[.18]",
  "auth-password-toggle": "absolute right-[5px] top-1/2 flex h-9 w-9 -translate-y-1/2 items-center justify-center rounded-sm border-0 bg-transparent p-2 text-[#b9aea3] hover:text-[#f3eee5] focus-visible:outline focus-visible:outline-2 focus-visible:outline-[#d78b5a]",
  "auth-password-icon": "h-[18px] w-[18px]",
  "auth-forgot-link": "self-end text-[8px] text-[#d78b5a] underline underline-offset-[2px]",
  "auth-password-row": "mt-[6px] flex items-center justify-between text-[9px] font-semibold text-[#f0e9df]",
  "auth-check": "my-[3px] mb-0 flex items-center gap-[7px] text-[8px] text-[#c5bbb0]",
  "auth-checkbox": "m-0 h-[13px] w-[13px] accent-[#d78b5a]",
  "auth-hint": "mb-[3px] mt-[-3px] text-[9px] leading-[1.6] text-[#897a6d]",
  "auth-submit": "relative mt-[9px] flex min-h-[39px] w-full items-center justify-center rounded-full border border-[#f2ede3] bg-[#f2ede3] px-[17px] text-[9px] font-semibold text-[#211f1e] transition hover:-translate-y-px hover:bg-white disabled:cursor-wait disabled:opacity-[.66] [&>span:last-child]:absolute [&>span:last-child]:right-[17px]",
  "auth-error": "my-[5px] border-l-[3px] border-[#a33e2b] px-[10px] py-2 text-[10px] leading-[1.6] text-[#8d3526]",
  "auth-success": "my-[5px] border-l-[3px] border-[#58704d] bg-[#edf1e8] px-[10px] py-2 text-[10px] leading-[1.6] text-[#40543b]",
  "auth-notice": "mb-[13px] flex flex-wrap items-center justify-between gap-2 bg-[#392d25] px-[11px] py-[10px] text-[8px] text-[#f0e9df]",
  "auth-notice-detail": "w-full text-[9px] text-[#c5bbb0]",
  "auth-notice-button": "ml-auto border-0 bg-transparent text-[8px] font-bold text-[#e29a68] underline",
  "auth-terms": "m-0 mt-1 text-[9px] leading-[1.65] text-[#87796c]",
  "auth-switch": "mt-[18px] text-center text-[8px] text-[#c5bbb0]",
  "auth-switch-link": "font-bold text-[#d78b5a] underline underline-offset-[2px]",
  "auth-back": "mt-[25px] inline-block text-[8px] text-[#b5a99d] transition-colors hover:text-[#e29a68]",
  "account-page": "min-h-screen bg-[#fbf1e2] text-espresso",
  "account-header": "flex min-h-[76px] items-center justify-between border-b border-[#dfcdb9] px-[7%] max-[420px]:px-[5%]",
  "account-brand": "flex items-center gap-[10px] text-[11px] font-bold tracking-[1.2px]",
  "account-brand-img": "h-11 w-11 rounded-full",
  "account-brand-role": "text-[8px] tracking-[1px] text-[#9b5d32]",
  "account-signout": "min-h-[37px] border border-[#c4a98d] bg-transparent px-[14px] text-[10px] text-[#57321f] transition-colors hover:bg-[#f2e4d2]",
  "account-card": "mx-auto my-[10vh] w-[calc(100%-40px)] max-w-[680px] border border-[#e5d6c3] bg-[#fffaf2] p-[clamp(28px,6vw,58px)]",
  "account-card-title": "mb-[11px] text-[clamp(30px,4vw,41px)] font-medium leading-[1.15] tracking-[-1.7px]",
  "account-card-copy": "mb-[27px] max-w-[480px] text-xs leading-[1.8] text-[#78685a]",

  "customer-dashboard": "flex min-h-screen bg-paper text-ink max-[680px]:block",
  "admin-sections": "grid gap-[17px]",
  "admin-overview-page": "grid gap-[18px]",
  "admin-overview-heading": "flex items-center justify-between gap-4 border-b border-[#e8eaf0] pb-[17px] [&_.dashboard-eyebrow]:mb-1 [&_.dashboard-eyebrow]:text-[8px] [&_h1]:m-0 [&_h1]:text-[25px] [&_h1]:font-semibold [&_h1]:tracking-[-.5px] [&_h1]:text-[#17191e]",
  "admin-create-order": "inline-flex min-h-[39px] items-center gap-2 rounded-[4px] bg-[#6954e8] px-[15px] text-[10px] font-medium text-white transition hover:bg-[#5540d2] [&_span]:text-[15px]",
  "admin-kpis": "grid grid-cols-4 gap-[13px] max-[900px]:grid-cols-2 max-[560px]:grid-cols-1",
  "admin-kpi": "relative min-w-0 overflow-hidden rounded-[7px] border border-[#e9e7f1] bg-white px-[17px] pb-[15px] pt-[14px] shadow-[0_2px_9px_rgb(27_31_45/.035)] transition duration-200 hover:-translate-y-[2px] hover:border-[#d8d3f3] hover:shadow-[0_8px_22px_rgb(27_31_45/.075)] [&>strong]:mt-[15px] [&>strong]:block [&>strong]:overflow-hidden [&>strong]:text-ellipsis [&>strong]:whitespace-nowrap [&>strong]:text-[clamp(18px,1.8vw,24px)] [&>strong]:font-semibold [&>strong]:leading-none [&>strong]:tracking-[-.7px] [&>strong]:text-[#191a22] [&:first-child]:before:absolute [&:first-child]:before:inset-x-0 [&:first-child]:before:top-0 [&:first-child]:before:h-[3px] [&:first-child]:before:bg-[#6954e8]",
  "admin-kpi-top": "flex min-w-0 items-center justify-between gap-2 [&>p]:m-0 [&>p]:truncate [&>p]:text-[9px] [&>p]:font-medium [&>p]:tracking-[.15px] [&>p]:text-[#777b88]",
  "admin-kpi-icon": "flex h-[30px] w-[30px] shrink-0 items-center justify-center rounded-[7px] bg-[#f1efff] text-[#6954e8] [&>svg]:h-[15px] [&>svg]:w-[15px] [&>svg]:stroke-current [&:nth-child(2)]:bg-[#eef6f1] [&:nth-child(2)]:text-[#498466]",
  "admin-kpi-note": "mt-[11px] flex items-center gap-[6px] overflow-hidden text-ellipsis whitespace-nowrap text-[8px] text-[#9093a0] [&>i]:h-[5px] [&>i]:w-[5px] [&>i]:shrink-0 [&>i]:rounded-full [&>i]:bg-[#80b894]",
  "admin-analytics-grid": "grid grid-cols-2 gap-[14px] max-[820px]:grid-cols-1",
  "admin-analytics-card": "min-w-0 rounded-[5px] border border-[#e8eaf0] bg-white p-[15px_16px_10px]",
  "admin-card-heading": "flex items-start justify-between gap-3 [&_h2]:m-0 [&_h2]:text-[13px] [&_h2]:font-semibold [&_h2]:text-[#1d2026] [&_p]:mb-0 [&_p]:mt-[4px] [&_p]:text-[8px] [&_p]:text-[#8b909a] [&>span]:rounded-[3px] [&>span]:border [&>span]:border-[#e7e9ef] [&>span]:px-[8px] [&>span]:py-[6px] [&>span]:text-[8px] [&>span]:text-[#6d727e]",
  "admin-chart-wrap": "relative mt-[9px] min-h-[190px]",
  "admin-chart": "block h-[176px] w-full overflow-visible",
  "admin-chart-axis-label": "fill-[#8b909a] text-[9px]",
  "admin-chart-day-label": "fill-[#7d838e] text-[9px]",
  "admin-chart-tooltip": "absolute right-[5px] top-[2px] z-10 grid gap-[3px] rounded-[4px] border border-[#eceef3] bg-white px-[8px] py-[6px] text-[8px] text-[#454a54] shadow-[0_3px_12px_rgb(25_32_25/.1)] [&>span]:mb-[2px] [&>strong]:flex [&>strong]:items-center [&>strong]:gap-[5px] [&>strong]:font-medium [&>strong>i]:h-[5px] [&>strong>i]:w-[5px] [&>strong>i]:rounded-full [&>strong:first-of-type>i]:bg-[#6a59e8] [&>strong:last-of-type>i]:bg-[#c8d0df]",
  "admin-chart-legend": "flex justify-center gap-[15px] pt-[1px] text-[8px] text-[#777e89] [&>span]:flex [&>span]:items-center [&>span]:gap-[5px] [&_i]:h-[6px] [&_i]:w-[6px] [&_i]:rounded-full [&>span:first-child_i]:bg-[#6a59e8] [&>span:last-child_i]:bg-[#c8d0df]",
  "admin-chart-bar": "fill-[#6687ed] transition-[height] hover:fill-[#526fce]",
  "admin-chart-empty": "absolute inset-x-0 top-[58px] text-center text-[9px] text-[#8b909a]",
  "admin-order-list": "overflow-hidden rounded-[5px] border border-[#e8eaf0] bg-white",
  "admin-order-heading": "flex items-center justify-between gap-3 border-b border-[#eceef3] px-[15px] py-[12px] max-[620px]:flex-col max-[620px]:items-stretch [&_h2]:m-0 [&_h2]:text-[13px] [&_h2]:font-semibold [&_h2]:text-[#1d2026] [&_p]:mb-0 [&_p]:mt-[3px] [&_p]:text-[8px] [&_p]:text-[#9095a0]",
  "admin-order-search": "flex h-[33px] w-[205px] items-center gap-[7px] rounded-[4px] border border-[#e4e6eb] px-[9px] text-[#7c8290] max-[620px]:w-full [&>span]:text-[16px] [&>input]:min-w-0 [&>input]:flex-1 [&>input]:border-0 [&>input]:bg-transparent [&>input]:text-[9px] [&>input]:text-[#333842] [&>input]:outline-none [&>input]:placeholder:text-[#9b9faa]",
  "admin-order-table": "mt-0 [&_th]:bg-[#fafbfc] [&_th]:px-[13px] [&_th]:py-[10px] [&_th]:text-[8px] [&_th]:font-medium [&_th]:uppercase [&_th]:tracking-[.25px] [&_th]:text-[#7f8591] [&_td]:px-[13px] [&_td]:py-[11px] [&_td]:text-[9px] [&_td]:text-[#4a4f59] [&_td>strong]:font-semibold [&_td>strong]:text-[#343943] [&_tr:last-child>td]:border-b-0",
  "admin-status-pill": "inline-flex rounded-full px-[9px] py-[5px] text-[7px] font-semibold uppercase tracking-[.2px]",
  "admin-order-pagination": "flex items-center justify-between border-t border-[#eceef3] px-[15px] py-[9px] text-[8px] text-[#828793] [&_div]:flex [&_div]:gap-[5px] [&_button]:h-[25px] [&_button]:w-[25px] [&_button]:rounded-[3px] [&_button]:border [&_button]:border-[#e4e6eb] [&_button]:bg-white [&_button]:text-[14px] [&_button]:text-[#545a66] [&_button:disabled]:cursor-not-allowed [&_button:disabled]:opacity-40",
  "admin-stock-alert": "rounded-[4px] border border-[#f1e0b8] bg-[#fff9eb] px-[12px] py-[10px] text-[9px] text-[#8f6b20] hover:bg-[#fff4da]",
  "admin-catalog-navigation": "min-w-0 overflow-hidden rounded-[6px] border border-[#e8eaf0] bg-white",
  "admin-catalog-tabs": "flex gap-1 overflow-x-auto px-[10px] pt-[8px] max-[680px]:px-[6px]",
  "admin-catalog-tab": "relative inline-flex min-h-[42px] shrink-0 items-center gap-[7px] border-0 border-b-2 border-transparent bg-transparent px-[11px] text-[9px] font-medium text-[#777e89] transition hover:text-[#344c35] [&>span]:rounded-full [&>span]:bg-[#f0f2f5] [&>span]:px-[6px] [&>span]:py-[2px] [&>span]:text-[7px] [&>span]:text-[#777e89]",
  "admin-catalog-tab-active": "border-b-[#557b52] text-[#385f39] [&>span]:bg-[#edf5ec] [&>span]:text-[#416743]",
  "admin-catalog-panel": "min-w-0 [&>section]:mb-0 [&>section]:rounded-[6px] [&>section]:border-[#e8eaf0] [&>section]:bg-white [&>section]:p-[17px] max-[680px]:[&>section]:p-[13px]",
  "admin-catalog-hint": "mb-0 mt-[10px] text-[8px] leading-relaxed text-[#858b95]",
  "admin-product-image-picker": "grid grid-cols-[58px_minmax(0,1fr)] items-center gap-x-[10px] gap-y-[4px] rounded-[5px] border border-dashed border-[#d9dce3] bg-[#fafbfc] p-[8px] [&>img]:row-span-3 [&>img]:h-[54px] [&>img]:w-[54px] [&>img]:rounded-[4px] [&>img]:bg-[#f0eee8] [&>img]:object-cover [&>span]:overflow-hidden [&>span]:text-ellipsis [&>span]:whitespace-nowrap [&>span]:text-[8px] [&>span]:text-[#5f6570] [&>input]:min-w-0 [&>input]:text-[8px] [&>input]:text-[#565c67] [&>input::file-selector-button]:mr-[7px] [&>input::file-selector-button]:min-h-[27px] [&>input::file-selector-button]:cursor-pointer [&>input::file-selector-button]:rounded-[4px] [&>input::file-selector-button]:border [&>input::file-selector-button]:border-[#dfe2e7] [&>input::file-selector-button]:bg-white [&>input::file-selector-button]:px-[9px] [&>input::file-selector-button]:text-[8px] [&>small]:text-[7px] [&>small]:text-[#9297a0]",
  "admin-pos-layout": "grid grid-cols-[minmax(0,1fr)_minmax(330px,390px)] items-start gap-[16px] max-[980px]:grid-cols-1",
  "admin-pos-products": "min-w-0 rounded-[7px] border border-[#e8eaf0] bg-white p-[16px] max-[640px]:p-[12px]",
  "admin-pos-products-heading": "flex items-center justify-between gap-3 [&_h2]:m-0 [&_h2]:text-[15px] [&_h2]:font-semibold [&_h2]:text-[#20232a] [&_p]:mb-0 [&_p]:mt-1 [&_p]:text-[9px] [&_p]:text-[#8b909a]",
  "admin-pos-search": "flex h-[34px] w-[190px] items-center gap-2 rounded-[5px] border border-[#e5e7ec] px-[9px] text-[#77808c] max-[540px]:w-[145px] [&>span]:text-[17px] [&>input]:min-w-0 [&>input]:flex-1 [&>input]:border-0 [&>input]:bg-transparent [&>input]:text-[9px] [&>input]:outline-none [&>input]:placeholder:text-[#9b9faa]",
  "admin-category-list": "mt-[16px] flex gap-[7px] overflow-x-auto pb-[5px] [&>button]:shrink-0",
  "admin-category-chip": "min-h-[29px] rounded-[5px] border border-transparent bg-[#f6f7f9] px-[10px] text-[8px] text-[#4e535e] transition hover:border-[#a9bea8] hover:bg-[#f2f8f1]",
  "admin-category-chip-active": "border-[#52764f] bg-white text-[#375d35] shadow-[inset_0_0_0_1px_#52764f]",
  "admin-pos-product-grid": "mt-[11px] grid grid-cols-4 gap-[11px] max-[1250px]:grid-cols-3 max-[1050px]:grid-cols-2 max-[540px]:grid-cols-1",
  "admin-pos-product-card": "min-w-0 cursor-pointer overflow-hidden rounded-[7px] border border-[#eceef2] bg-white p-[6px] text-left transition hover:border-[#a9bea8] hover:shadow-[0_4px_14px_rgb(25_32_25/.08)] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#557b52] aria-disabled:cursor-not-allowed aria-disabled:opacity-60",
  "admin-pos-product-image": "relative flex aspect-[1.28] items-center justify-center overflow-hidden rounded-[6px] bg-[#f0eee8] [&>img]:h-full [&>img]:w-full [&>img]:object-cover [&>span:first-child]:text-[40px]",
  "admin-pos-availability": "absolute left-[7px] top-[7px] rounded-full bg-[#e7f6ec] px-[8px] py-[4px] text-[7px] font-semibold text-[#28864c]",
  "admin-pos-product-info": "grid gap-[4px] px-[4px] pt-[8px] [&>strong]:overflow-hidden [&>strong]:text-ellipsis [&>strong]:whitespace-nowrap [&>strong]:text-[10px] [&>strong]:font-semibold [&>strong]:text-[#292d34] [&>span]:overflow-hidden [&>span]:text-ellipsis [&>span]:whitespace-nowrap [&>span]:text-[8px] [&>span]:text-[#858b95]",
  "admin-pos-product-actions": "mt-[8px] flex items-center justify-between gap-2 border-t border-[#f0f1f4] px-[4px] pt-[7px] [&>b]:text-[10px] [&>b]:font-semibold [&>b]:text-[#30343b] [&>span]:text-[7px] [&>span]:text-[#858b95]",
  "admin-pos-product-sizes": "overflow-hidden text-ellipsis whitespace-nowrap rounded-[3px] bg-[#f2f6f1] px-[5px] py-[3px] text-[7px] text-[#557b52]",
  "admin-pos-empty": "col-span-full rounded-[5px] bg-[#fafbfc] px-[16px] py-[36px] text-center text-[10px] leading-relaxed text-[#818792]",
  "admin-pos-order": "sticky top-[12px] max-h-[calc(100vh-24px)] overflow-y-auto rounded-[7px] border border-[#e8eaf0] bg-white p-[14px] max-[980px]:static max-[980px]:max-h-none max-[640px]:p-[12px]",
  "admin-pos-order-heading": "flex items-start justify-between gap-2 [&_h2]:m-0 [&_h2]:text-[15px] [&_h2]:font-semibold [&_h2]:text-[#20232a] [&_span]:mt-[5px] [&_span]:block [&_span]:text-[8px] [&_span]:text-[#858b95]",
  "admin-pos-clear": "border-0 bg-transparent p-1 text-[8px] text-[#b5534c] underline underline-offset-2 disabled:opacity-40",
  "admin-pos-customer": "mt-[12px] rounded-[6px] border border-[#eceef2] p-[10px] [&>h3]:mb-[8px] [&>h3]:mt-0 [&>h3]:text-[10px] [&>h3]:font-semibold [&>h3]:text-[#343943]",
  "admin-pos-customer-field": "grid min-w-0 gap-[4px] rounded-[5px] bg-[#f7f8fa] px-[8px] py-[6px] [&>span]:text-[7px] [&>span]:text-[#858b95] [&>select]:w-full [&>select]:border-0 [&>select]:bg-transparent [&>select]:text-[9px] [&>select]:text-[#30343b] [&>select]:outline-none",
  "admin-pos-select-row": "mt-[6px] grid grid-cols-2 gap-[6px] max-[430px]:grid-cols-1",
  "admin-pos-cart": "mt-[8px] max-h-[330px] overflow-y-auto",
  "admin-pos-cart-item": "grid grid-cols-[38px_minmax(0,1fr)_auto] gap-[8px] border-b border-[#eceef2] py-[9px]",
  "admin-pos-cart-thumb": "flex h-[38px] w-[38px] items-center justify-center overflow-hidden rounded-[5px] bg-[#f0eee8] text-[20px] [&>img]:h-full [&>img]:w-full [&>img]:object-cover",
  "admin-pos-cart-copy": "grid min-w-0 content-start gap-[3px] [&>strong]:overflow-hidden [&>strong]:text-ellipsis [&>strong]:whitespace-nowrap [&>strong]:text-[9px] [&>strong]:font-semibold [&>strong]:text-[#343943] [&>span]:text-[7px] [&>span]:text-[#858b95]",
  "admin-pos-customize": "text-[8px] text-[#53794f] [&>summary]:w-fit [&>summary]:cursor-pointer [&>summary]:font-medium [&_label]:mt-[6px] [&_label]:grid [&_label]:gap-[4px] [&_label>span]:text-[7px] [&_label>select]:min-h-[42px] [&_label>select]:w-full [&_label>select]:rounded-[4px] [&_label>select]:border [&_label>select]:border-[#e4e6eb] [&_label>select]:bg-white [&_label>select]:p-1 [&_label>select]:text-[8px]",
  "admin-pos-variation": "mt-[5px] grid gap-[3px] [&>span]:text-[7px] [&>span]:text-[#858b95] [&>select]:h-[25px] [&>select]:w-full [&>select]:rounded-[4px] [&>select]:border [&>select]:border-[#e4e6eb] [&>select]:bg-white [&>select]:px-[5px] [&>select]:text-[8px]",
  "admin-pos-quantity": "mt-[5px] flex w-fit items-center overflow-hidden rounded-[4px] border border-[#e4e6eb] [&>button]:h-[22px] [&>button]:w-[24px] [&>button]:border-0 [&>button]:bg-[#f6f7f9] [&>button]:text-[12px] [&>button:disabled]:opacity-45 [&>span]:min-w-[22px] [&>span]:text-center [&>span]:text-[8px] [&>span]:text-[#424751]",
  "admin-pos-line-total": "flex flex-col items-end justify-between [&>button]:border-0 [&>button]:bg-transparent [&>button]:text-[15px] [&>button]:leading-none [&>button]:text-[#8d929c] [&>button:disabled]:opacity-40 [&>strong]:whitespace-nowrap [&>strong]:text-[9px] [&>strong]:font-semibold [&>strong]:text-[#343943]",
  "admin-pos-cart-empty": "my-[10px] rounded-[5px] bg-[#fafbfc] px-[10px] py-[18px] text-center text-[8px] text-[#858b95]",
  "admin-pos-promo": "mt-[8px] flex items-center justify-between border-b border-[#eceef2] py-[8px] [&>label]:flex [&>label]:min-w-0 [&>label]:items-center [&>label]:gap-[7px] [&>label>span]:text-[11px] [&>label>span]:text-[#4b9e62] [&_select]:min-w-0 [&_select]:border-0 [&_select]:bg-transparent [&_select]:text-[8px] [&_select]:text-[#4b515b] [&_select]:outline-none [&>button]:border-0 [&>button]:bg-transparent [&>button]:text-[7px] [&>button]:text-[#68717d] [&>button]:underline",
  "admin-pos-notes": "mt-[7px] grid gap-[4px] [&>span]:text-[7px] [&>span]:text-[#858b95] [&>input]:h-[29px] [&>input]:w-full [&>input]:rounded-[4px] [&>input]:border [&>input]:border-[#e8eaf0] [&>input]:px-[8px] [&>input]:text-[8px] [&>input]:outline-none [&>input:focus]:border-[#8aa486]",
  "admin-pos-totals": "mt-[7px] grid gap-[5px] [&>div]:flex [&>div]:items-center [&>div]:justify-between [&>div]:text-[8px] [&>div>span]:text-[#717783] [&>div>strong]:font-medium [&>div>strong]:text-[#424751]",
  "admin-pos-grand-total": "mt-[3px] border-t border-[#e8eaf0] pt-[8px] [&>span]:font-semibold [&>span]:text-[#30343b] [&>strong]:text-[12px] [&>strong]:font-bold [&>strong]:text-[#20232a]",
  "admin-pos-tender": "mt-[9px] grid grid-cols-2 gap-[7px] max-[430px]:grid-cols-1 [&_label]:grid [&_label]:gap-[4px] [&_label>span]:text-[7px] [&_label>span]:text-[#858b95] [&_select]:h-[31px] [&_select]:w-full [&_select]:rounded-[4px] [&_select]:border [&_select]:border-[#e5e7ec] [&_select]:bg-white [&_select]:px-[7px] [&_select]:text-[8px] [&_input]:h-[31px] [&_input]:w-full [&_input]:rounded-[4px] [&_input]:border [&_input]:border-[#e5e7ec] [&_input]:px-[7px] [&_input]:text-[8px]",
  "admin-pos-pending-note": "mt-[9px] rounded-[4px] bg-[#fff7e8] p-[8px] text-[8px] leading-relaxed text-[#8c6924]",
  "admin-pos-checkout": "mt-[10px] inline-flex min-h-[39px] w-full items-center justify-center gap-[8px] rounded-[5px] border-0 bg-[#315c37] text-[9px] font-semibold text-white transition hover:bg-[#274c2d] disabled:cursor-not-allowed disabled:opacity-50 [&>span]:text-[11px]",
  "admin-overview-stat": "min-h-[118px]",
  "admin-overview-grid": "grid grid-cols-2 gap-[17px] max-[900px]:grid-cols-1",
  "admin-resource-panel": "mb-[17px] p-[20px_21px] max-[680px]:px-[14px] max-[680px]:pb-[15px] max-[680px]:pt-4",
  "admin-count": "whitespace-nowrap rounded-[20px] bg-[#f4f1e9] px-[9px] py-[6px] text-[8px] text-[#77776d]",
  "admin-record-form": "mt-5 grid grid-cols-2 items-end gap-[13px] max-[680px]:grid-cols-1",
  "admin-field": "grid min-w-0 gap-[6px] text-[9px] font-semibold text-[#666157] [&>input]:min-h-[36px] [&>input]:w-full [&>input]:border [&>input]:border-[#ddd5c9] [&>input]:bg-[#fffdf9] [&>input]:px-[10px] [&>input]:text-[10px] [&>input]:text-ink [&>input:focus]:border-[#a96941] [&>input:focus]:outline-none [&>select]:min-h-[36px] [&>select]:w-full [&>select]:border [&>select]:border-[#ddd5c9] [&>select]:bg-[#fffdf9] [&>select]:px-[10px] [&>select]:text-[10px] [&>select]:text-ink [&>textarea]:min-h-[68px] [&>textarea]:w-full [&>textarea]:resize-y [&>textarea]:border [&>textarea]:border-[#ddd5c9] [&>textarea]:bg-[#fffdf9] [&>textarea]:px-[10px] [&>textarea]:py-[8px] [&>textarea]:text-[10px] [&>textarea]:text-ink",
  "admin-field-wide": "col-span-2 max-[680px]:col-span-1",
  "admin-field-checkbox": "flex min-h-[37px] items-center gap-[8px] text-[9px] font-medium [&>input]:h-[14px] [&>input]:w-[14px] [&>input]:accent-[#9b5d32]",
  "admin-product-pricing": "col-span-2 grid gap-[12px] rounded-[5px] border border-[#ece6dc] bg-[#fcfaf6] p-[12px] max-[680px]:col-span-1",
  "admin-product-size-editor": "grid gap-[9px] [&>div:first-child]:grid [&>div:first-child]:gap-[3px] [&>div:first-child>strong]:text-[10px] [&>div:first-child>strong]:text-[#4c3b2c] [&>div:first-child>span]:text-[8px] [&>div:first-child>span]:text-[#82766a]",
  "admin-product-size-row": "grid grid-cols-[1.2fr_1fr_auto_auto] items-end gap-[9px] rounded-[4px] border border-[#eee8df] bg-white p-[9px] [&_label]:grid [&_label]:gap-[5px] [&_label>span]:text-[8px] [&_label>span]:text-[#71685e] [&_input:not([type=checkbox])]:min-h-[34px] [&_input:not([type=checkbox])]:w-full [&_input:not([type=checkbox])]:border [&_input:not([type=checkbox])]:border-[#ddd5c9] [&_input:not([type=checkbox])]:bg-[#fffdf9] [&_input:not([type=checkbox])]:px-[8px] [&_input:not([type=checkbox])]:text-[9px] [&_select]:min-h-[34px] [&_select]:w-full [&_select]:border [&_select]:border-[#ddd5c9] [&_select]:bg-[#fffdf9] [&_select]:px-[8px] [&_select]:text-[9px] [&_select]:text-ink max-[680px]:grid-cols-2",
  "admin-input": "min-h-[36px] w-full border border-[#ddd5c9] bg-[#fffdf9] px-[10px] text-[10px] text-ink focus:border-[#a96941] focus:outline-none focus:ring-2 focus:ring-[#d5a477]/30",
  "admin-form-actions": "col-span-2 flex flex-wrap gap-[9px] max-[680px]:col-span-1",
  "admin-primary-button": "min-h-[36px] border border-espresso bg-espresso px-[14px] text-[9px] font-semibold text-white transition hover:bg-[#572d1c] disabled:cursor-wait disabled:opacity-60",
  "admin-secondary-button": "min-h-[36px] border border-[#c4a98d] bg-transparent px-[13px] text-[9px] text-[#57321f] transition hover:bg-[#f2e4d2] disabled:cursor-wait disabled:opacity-60",
  "admin-text-button": "mr-2 border-0 bg-transparent p-0 text-[9px] font-semibold text-[#8c5a3d] underline underline-offset-2 hover:text-espresso disabled:opacity-50",
  "admin-delete-button": "text-[#a33e2b]",
  "admin-form-error": "col-span-2 m-0 border-l-[3px] border-[#ad4c3f] bg-[#fbefed] px-[10px] py-[8px] text-[9px] text-[#853b31] max-[680px]:col-span-1",
  "admin-success-toast": "fixed right-5 top-5 z-[100] flex min-h-[46px] items-center gap-[10px] rounded-[5px] border border-[#cce5d0] bg-white px-[14px] py-[10px] text-[10px] text-[#315d39] shadow-[0_8px_28px_rgb(25_32_25/.16)] [&>span]:flex [&>span]:h-[20px] [&>span]:w-[20px] [&>span]:items-center [&>span]:justify-center [&>span]:rounded-full [&>span]:bg-[#e7f5e9] [&>span]:font-bold [&>button]:ml-[8px] [&>button]:border-0 [&>button]:bg-transparent [&>button]:text-[16px] [&>button]:text-[#758477] max-[680px]:left-4 max-[680px]:right-4 max-[680px]:top-4",
  "admin-form-help": "mt-3 text-[9px] leading-[1.6] text-[#82766a]",
  "admin-table-wrap": "mt-5 w-full overflow-x-auto",
  "admin-table": "w-full border-collapse text-left text-[9px] [&_th]:whitespace-nowrap [&_th]:border-b [&_th]:border-[#e9e3da] [&_th]:px-[10px] [&_th]:py-[9px] [&_th]:font-bold [&_th]:capitalize [&_th]:tracking-[.3px] [&_th]:text-[#867b6e] [&_td]:border-b [&_td]:border-[#f0eee8] [&_td]:px-[10px] [&_td]:py-[10px] [&_td]:text-[#57544e]",
  "admin-table-empty": "py-8 text-center text-[#888277]",
  "admin-row-actions": "flex whitespace-nowrap",
  "admin-order-line": "col-span-2 grid grid-cols-[2fr_1.5fr_0.8fr_auto] items-end gap-[10px] border-t border-[#eee8df] pt-3 max-[680px]:col-span-1 max-[680px]:grid-cols-1",
  "admin-refund-list": "mt-4 grid gap-[9px]",
  "admin-refund-form": "grid grid-cols-[1.2fr_1fr_2fr_auto] items-center gap-[8px] border-t border-[#eee8df] pt-[10px] text-[9px] [&>input]:min-h-[36px] [&>input]:w-full [&>input]:border [&>input]:border-[#ddd5c9] [&>input]:bg-[#fffdf9] [&>input]:px-[10px] [&>input]:text-[10px] max-[680px]:grid-cols-1",
  "admin-report-filter": "mt-4 grid grid-cols-[1fr_1fr_auto] items-end gap-[12px] max-[680px]:grid-cols-1",
  "admin-report-list": "mt-3",
  "admin-report-row": "grid grid-cols-[1.4fr_1fr_1fr] gap-3 border-t border-[#eee8df] py-[11px] text-[9px] [&>strong]:font-medium [&>strong]:text-[#51473e] [&>span]:text-[#82766a] [&>b]:text-right [&>b]:font-semibold [&>b]:text-espresso",
  "admin-low-stock-list": "mt-4 grid gap-0",
  "admin-low-stock-row": "flex justify-between gap-3 border-t border-[#eee8df] py-[10px] text-[9px] [&>strong]:font-medium [&>span]:text-right [&>span]:text-[#8c5a3d]",
  "admin-empty-copy": "my-4 text-[10px] leading-[1.6] text-[#82766a]",
  "admin-service-error": "mb-4 flex items-center justify-between gap-3 border-l-[3px] border-[#ad4c3f] bg-[#fbefed] px-[13px] py-[10px] text-[10px] text-[#853b31]",
  "admin-loading": "py-8 text-center text-xs text-[#78685a]",
  "dashboard-sidebar": "sticky top-0 flex h-screen max-h-screen min-h-0 w-[252px] shrink-0 self-start flex-col overflow-y-auto bg-[#252320] px-[18px] pb-[17px] pt-7 text-[#f5f0e8] shadow-[inset_-1px_0_rgba(255,255,255,.04)] max-[900px]:w-[218px] max-[680px]:static max-[680px]:h-auto max-[680px]:max-h-none max-[680px]:min-h-0 max-[680px]:w-full max-[680px]:overflow-visible max-[680px]:px-4 max-[680px]:pb-0 max-[680px]:pt-3",
  "dashboard-brand": "mb-[54px] ml-2 mr-2 flex items-center gap-[10px] max-[680px]:mb-3 max-[680px]:ml-[2px] max-[680px]:mr-[2px]",
  "dashboard-brand-img": "h-[38px] w-[38px] rounded-full border border-white/55 object-cover",
  "dashboard-brand-text": "text-[11px] font-bold tracking-[1.4px]",
  "dashboard-brand-accent": "font-medium not-italic text-[#c89c70]",
  "dashboard-nav-label": "mb-3 ml-[10px] mr-[10px] text-[9px] font-bold tracking-[1.4px] text-[#c4a17f] max-[680px]:hidden",
  "dashboard-nav": "grid gap-[5px] max-[680px]:mx-[-16px] max-[680px]:flex max-[680px]:gap-1 max-[680px]:overflow-x-auto max-[680px]:px-3 max-[680px]:pb-[10px]",
  "dashboard-nav-link": "flex min-h-11 items-center gap-3 rounded-[5px] px-3 text-xs text-[#c9c2b8] transition-colors hover:bg-white/[.07] hover:text-[#fffdf7] max-[680px]:min-h-[38px] max-[680px]:flex-none max-[680px]:gap-[7px] max-[680px]:px-[10px] max-[680px]:text-[10px]",
  "dashboard-nav-link-active": "bg-[#37332e] text-[#fffdf7] shadow-[inset_2px_0_#c89c70] max-[680px]:shadow-[inset_0_-2px_#c89c70]",
  "dashboard-nav-icon": "h-[18px] w-[18px] shrink-0",
  "dashboard-user": "max-[680px]:hidden",
  "route-state": "flex min-h-screen flex-col items-center justify-center bg-[#fbf1e2] p-7 text-center text-espresso [&>p]:max-w-[420px] [&>p]:text-xs [&>p]:leading-[1.7] [&>p]:text-[#78685a] [&>.auth-submit]:max-w-[170px] [&>.auth-submit]:justify-center",
  "dashboard-chart-wrap": "mt-1 h-[185px] w-full max-[680px]:h-40",
  "dashboard-chart-legend": "flex items-center justify-between border-t border-[#f0efe9] pt-[11px] text-[8px] text-[#999a91] max-[680px]:flex-col max-[680px]:items-start max-[680px]:gap-[7px]",
  "dashboard-stat-label": "mb-3 text-[10px] text-[#7d7f76] max-[680px]:mb-2",
  "dashboard-stat-value": "mb-2 block text-[25px] font-medium leading-[1.15] tracking-[-.6px] text-espresso max-[680px]:mb-[5px] max-[680px]:text-[22px]",
  "dashboard-stat-value-small": "text-xl max-[680px]:text-lg",
  "dashboard-activity": "mb-[17px] p-[20px_21px_14px] max-[680px]:px-[14px] max-[680px]:pb-[13px] max-[680px]:pt-4",
  "dashboard-recent": "p-[19px_21px] max-[680px]:px-[14px] max-[680px]:pb-[13px] max-[680px]:pt-4",
  "dashboard-chart-legend-label": "flex items-center gap-[7px] text-[#8b5334]",
  "dashboard-empty-order": "mt-4 flex items-center gap-[13px] border-t border-[#f0efe9] pt-[15px] max-[680px]:flex-wrap max-[680px]:items-start",
  "dashboard-empty-copy": "flex-1 max-[680px]:basis-[calc(100%-55px)]",
  "dashboard-empty-order-link": "whitespace-nowrap text-[9px] text-[#7b6447] max-[680px]:ml-[51px]",
  "dashboard-sidebar-order": "mb-[22px] ml-[2px] mr-[2px] mt-auto grid gap-[10px] rounded-md border border-white/10 bg-white/[.06] px-[13px] py-[15px] max-[680px]:hidden",
  "dashboard-sidebar-order-copy": "text-[10px] text-[#c0c8bf]",
  "dashboard-sidebar-order-cta": "flex items-center justify-between text-[11px] font-semibold text-[#e5bd92]",
  "dashboard-sidebar-user": "flex items-center gap-[10px] border-t border-white/[.13] px-[3px] pt-4 max-[680px]:hidden",
  "dashboard-avatar": "inline-flex h-[34px] w-[34px] flex-[0_0_34px] items-center justify-center rounded-full bg-caramel text-[10px] font-bold text-espresso",
  "dashboard-user-copy": "grid min-w-0 gap-[3px]",
  "dashboard-user-name": "overflow-hidden text-ellipsis whitespace-nowrap text-[10px] text-[#fbf1e2]",
  "dashboard-user-subtitle": "text-[9px] text-[#c1a991]",
  "dashboard-signout-icon": "ml-auto inline-flex h-[34px] w-[34px] items-center justify-center border-0 bg-transparent text-[#d3c2b2] hover:text-white",
  "dashboard-signout-svg": "h-[17px] w-[17px]",
  "dashboard-main": "min-w-0 flex-1",
  "dashboard-topbar": "flex h-[58px] items-center justify-between border-b border-[#e8eaf0] bg-white px-[clamp(24px,4.5vw,66px)] max-[680px]:h-12 max-[680px]:px-[18px]",
  "admin-header-brown": "!border-[#51443a] !bg-[linear-gradient(105deg,#403b35_0%,#625044_52%,#75543e_100%)]",
  "admin-header-breadcrumb": "!text-[#fffaf3]",
  "admin-header-breadcrumb-muted": "!text-[#eddfd2]",
  "admin-header-breadcrumb-slash": "!text-[#d2b8a1]",
  "admin-account-menu": "relative z-30",
  "admin-account-trigger": "flex min-w-0 items-center gap-[9px] border-0 bg-transparent px-[3px] py-[2px] text-left transition hover:opacity-80 [&:focus-visible]:rounded-[5px] [&:focus-visible]:outline [&:focus-visible]:outline-2 [&:focus-visible]:outline-[#d7d1f5]",
  "admin-header-avatar": "inline-flex h-[30px] w-[30px] shrink-0 items-center justify-center rounded-full bg-[#f0e4d5] text-[9px] font-semibold text-[#603c29]",
  "admin-header-account-copy": "grid min-w-0 gap-[2px] [&>strong]:max-w-[170px] [&>strong]:overflow-hidden [&>strong]:text-ellipsis [&>strong]:whitespace-nowrap [&>strong]:text-[9px] [&>strong]:font-semibold [&>strong]:text-[#fff8ef] [&>small]:overflow-hidden [&>small]:text-ellipsis [&>small]:whitespace-nowrap [&>small]:text-[7px] [&>small]:text-[#e0c7ad] max-[480px]:hidden",
  "admin-account-chevron": "h-[13px] w-[13px] shrink-0 text-[#e0c7ad] transition-transform",
  "admin-account-chevron-open": "rotate-180",
  "admin-account-dropdown": "absolute right-0 top-[calc(100%+9px)] w-[205px] overflow-hidden rounded-[6px] border border-[#e8eaf0] bg-white p-[5px] shadow-[0_8px_24px_rgb(25_32_25/.14)]",
  "admin-account-dropdown-user": "grid gap-[3px] border-b border-[#f0f1f4] px-[10px] py-[9px] [&>strong]:overflow-hidden [&>strong]:text-ellipsis [&>strong]:whitespace-nowrap [&>strong]:text-[9px] [&>strong]:font-semibold [&>strong]:text-[#30323a] [&>span]:overflow-hidden [&>span]:text-ellipsis [&>span]:whitespace-nowrap [&>span]:text-[8px] [&>span]:text-[#858b95]",
  "admin-account-dropdown-signout": "flex min-h-[34px] w-full items-center gap-[8px] rounded-[4px] border-0 bg-white px-[9px] text-left text-[9px] text-[#8c5a3d] transition hover:bg-[#faf6f2] [&>svg]:h-[14px] [&>svg]:w-[14px]",
  "dashboard-breadcrumb": "flex gap-[10px] text-[9px] font-semibold tracking-[1px] text-[#777970]",
  "dashboard-breadcrumb-muted": "text-[#a09f95]",
  "dashboard-breadcrumb-slash": "not-italic text-[#c2c0b5]",
  "dashboard-topbar-link": "text-[10px] text-[#8c5a3d] hover:text-caramel",
  "dashboard-content": "mx-auto max-w-[1440px] px-[clamp(24px,3.4vw,48px)] pb-[22px] pt-[25px] max-[900px]:px-7 max-[680px]:px-[18px] max-[680px]:pb-5 max-[680px]:pt-5",
  "dashboard-welcome": "mb-[29px] flex items-end justify-between gap-5 max-[680px]:mb-5 max-[680px]:items-start max-[680px]:flex-col",
  "dashboard-eyebrow": "mb-[11px] text-[9px] font-bold tracking-[1.7px] text-[#9b5d32]",
  "dashboard-welcome-title": "mb-2 text-[clamp(27px,3.4vw,37px)] font-medium leading-[1.15] tracking-[-1.3px] text-espresso",
  "dashboard-welcome-description": "m-0 text-[11px] leading-[1.7] text-muted",
  "dashboard-order-button": "inline-flex min-h-[42px] flex-none items-center justify-between gap-[22px] rounded border border-espresso bg-espresso px-[14px] text-[10px] text-[#fffdf7] transition hover:-translate-y-px hover:bg-[#572d1c] max-[680px]:min-h-[39px]",
  "dashboard-error": "mb-[18px] border-l-[3px] border-[#ad4c3f] bg-[#fbefed] px-[13px] py-[11px] text-[11px] text-[#853b31]",
  "dashboard-stat-grid": "mb-[17px] grid grid-cols-3 gap-[14px] max-[900px]:gap-[9px] max-[680px]:grid-cols-1",
  "dashboard-stat-card": "relative min-h-[148px] border border-[#e4d9cc] bg-white px-[18px] pb-[15px] pt-[17px] max-[900px]:px-[13px] max-[680px]:min-h-[118px] max-[680px]:p-[15px]",
  "dashboard-stat-note": "block text-[9px] leading-[1.5] text-[#a0a097]",
  "dashboard-stat-icon": "absolute right-4 top-[15px] flex h-[26px] w-7 items-center justify-center rounded-[5px] text-[8px]",
  "dashboard-stat-icon-green": "bg-[#f5e9dc] text-[#8a4b2d]",
  "dashboard-stat-icon-caramel": "bg-[#f6eee3] text-[#9b663a]",
  "dashboard-stat-icon-cream": "bg-[#f5f1e8] text-[15px] text-[#8e7751]",
  "dashboard-panel": "border border-[#e4d9cc] rounded-md bg-white",
  "dashboard-panel-heading": "flex items-center justify-between gap-[14px]",
  "dashboard-section-kicker": "mb-[6px] text-[8px] font-bold tracking-[1.4px] text-[#9b5d32]",
  "dashboard-panel-title": "m-0 text-[15px] font-semibold tracking-[-.2px] text-espresso",
  "dashboard-preview-tag": "whitespace-nowrap rounded-[20px] bg-[#f4f1e9] px-[9px] py-[6px] text-[8px] text-[#77776d]",
  "dashboard-chart-note": "mt-[9px] text-[9px] leading-[1.55] text-[#98988f]",
  "dashboard-chart": "h-full w-full overflow-visible",
  "dashboard-chart-grid": "stroke-[#eeeee8] [stroke-dasharray:3_5] [stroke-width:1]",
  "dashboard-chart-line": "fill-none stroke-caramel [stroke-linecap:round] [stroke-linejoin:round] [stroke-width:2.5] [vector-effect:non-scaling-stroke]",
  "dashboard-chart-point": "fill-white stroke-caramel [stroke-width:2] [vector-effect:non-scaling-stroke]",
  "dashboard-chart-label": "fill-[#92938b] [font-family:'DM_Sans',sans-serif] [font-size:9px]",
  "dashboard-chart-legend-dot": "h-[7px] w-[7px] rounded-full bg-caramel",
  "dashboard-recent-link": "whitespace-nowrap text-[9px] text-[#718072]",
  "dashboard-empty-icon": "inline-flex h-[38px] w-[38px] flex-[0_0_38px] items-center justify-center rounded-full bg-[#f5f2e9] text-[17px] text-[#9b5d32]",
  "dashboard-empty-order-title": "mb-1 block text-[10px] font-semibold text-[#45473f]",
  "dashboard-empty-order-description": "m-0 text-[9px] leading-[1.55] text-[#999990]",
  "dashboard-page-panel": "min-h-[340px] p-[25px]",
  "dashboard-empty-state": "mx-auto my-12 flex max-w-[380px] flex-col items-center text-center",
  "dashboard-empty-title": "mb-[7px] mt-[15px] text-[19px] font-semibold text-[#2d3d32]",
  "dashboard-empty-description": "mb-[17px] text-[11px] leading-[1.7] text-[#85867d]",
  "dashboard-profile-panel": "p-6",
  "dashboard-profile-title": "m-0 text-[15px] font-semibold text-espresso",
  "dashboard-profile-details": "mt-5",
  "dashboard-profile-row": "grid grid-cols-[minmax(110px,.4fr)_1fr] gap-3 border-t border-[#e4d9cc] py-[14px]",
  "dashboard-profile-label": "text-[10px] text-[#88897f]",
  "dashboard-profile-value": "m-0 [overflow-wrap:anywhere] text-[11px] text-espresso",
  "dashboard-profile-note": "mt-3 bg-[#f7f5ef] p-[11px] text-[9px] leading-[1.6] text-[#88897f]",
  "dashboard-footer": "pt-[22px] text-center text-[9px] text-[#a3a298]",

  eyebrow: "mb-[23px] flex items-center gap-[9px] text-[9px] font-bold tracking-[1.55px] text-rust [&>span]:inline-block [&>span]:h-px [&>span]:w-[23px] [&>span]:bg-rust",
  "eyebrow-light": "text-[#d89b72] [&>span]:bg-[#d89b72]",
  "button-dark": "bg-ink text-white transition-colors hover:bg-rust",
  button: "inline-flex items-center justify-between gap-6 px-[18px] py-4 text-[11px]",
  "text-link": "text-[11px] text-ink transition-colors hover:text-rust",
  "section-pad": "px-[10.5%] max-[900px]:px-[7%] max-[640px]:px-[6%]",
  "menu-number": "hidden",
  "visit-heading": "max-w-[480px] [&_.eyebrow]:mb-[18px]",
  "footer-wordmark": "gap-3 [&>img]:h-[50px] [&>img]:w-[50px] [&>span]:text-[13px] [&_small]:text-muted",
  "is-open": "max-[640px]:visible",
  "is-active": "",
  "admin-page": "",
  "auth-art-bean": "absolute bottom-10 right-10 h-14 w-8 rotate-[38deg] rounded-[50%] border border-[#c5a58a]/40",
  "dashboard-member-card": "",
  "dashboard-profile-heading": "m-0 text-[15px] font-semibold text-espresso",
  "auth-panel-title": "mb-[7px] text-[clamp(29px,3.6vw,36px)] font-medium leading-[1.15] tracking-[-1.3px] text-[#f5f0e8]",
  "auth-field-label": "mt-[6px] text-[9px] font-semibold text-[#f0e9df]",
  "auth-submit-arrow": "text-[15px]",
  "admin-preview-notice": "mb-[18px] border-l-[3px] border-caramel bg-[#f5eee4] px-[13px] py-[11px] text-[10px] leading-[1.6] text-[#75583f]",
  "admin-preview-tag": "whitespace-nowrap rounded-[20px] bg-[#f5eee4] px-[9px] py-[6px] text-[8px] text-[#8b6441]",
  "admin-feature-panel": "p-[22px] max-[680px]:p-[16px]",
  "admin-feature-list": "mb-0 mt-5 grid list-none gap-0 p-0",
  "admin-feature-item": "flex min-h-[43px] items-center gap-3 border-t border-[#f0eee8] py-[10px] text-[10px] leading-[1.5] text-[#5e6059]",
  "admin-feature-check": "text-base font-semibold text-[#9b5d32]",
  "admin-module-panel": "p-[22px] max-[680px]:p-[16px]",
  "admin-module-grid": "mt-4 grid grid-cols-2 gap-[10px] max-[680px]:grid-cols-1",
  "admin-module-link": "flex min-h-[48px] items-center justify-between border border-[#eee8df] bg-[#fffdf9] px-[13px] text-[10px] text-[#51473e] transition hover:border-[#d5a477] hover:bg-[#faf5ec]",
};

export function tw(classes: string): string {
  return classes
    .split(/\s+/)
    .filter(Boolean)
    .map((name) => utilities[name] ?? name)
    .join(" ");
}
